### ISSUE TITLE
Instructor Feedback Week 4

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [bvue/MyProject#3]
Hi Bao,

First thing... FANTASTIC job on your 1st extracurricular event/presentation. I know from your journal entries that you weren't very excited about being pushed to do this, but it seems like you did find something worthwhile that you might not have otherwise done (at least not at this point in time).  Your presentation, as you can see from your peer feedback, was very engaging. Well done!  

I also hear your concerns about the amount of work in the this class. The first weeks tend to be pretty intense with the setup and exercises, but I hope that moving forward with the option to complete weekly work within your project, things will level out for you a bit.  

How are you planning your weekly work and steps moving forward? If a detailed project plan doesn't work for you, at least a high level plan might help? What do you plan to accomplish during week 4? Is there a stretch goal for the week?

Please don't hesitate to reach out if you need any help!

**Comment by bvue** [comment]
Hey Paula, I am following the suggestions you have for us each week. Week 4, I completed jsps and java classes for my Money Manager app. However, I don't have all the fine detail on the java classes figured out yet because I'm having a hard time picturing what exactly my code will need. So far I am thinking some kind of array list to hold all of my different accounts and methods to add and subtract from those accounts. I would like to have a calendar portion in there too where I can set up monthly bills and pay days but I'm not exactly sure how to break that down. I also researched a bit on Struts as my additional research project. Updates on my project page to follow!
